# -*- coding: utf-8 -*-
"""UNEMPLOYMENT ANALYSIS WITH PYTHON

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1keNDuYj8n91vhspf2QVWgif75KORjn3m
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
data = pd.read_csv('/content/Unemployment in India.csv')
print(data.head())

data.tail()

data.sample()

data.dtypes

data.describe()

data.isnull().sum()

data.shape

data.dropna(axis=0,inplace=True)
data.isnull().sum()

data.columns

print(data.columns)

unemployment_rate_column = ' Estimated Unemployment Rate (%)'
plt.hist(data[unemployment_rate_column], bins=20, edgecolor='black')
plt.title('Distribution of Unemployment Rates')
plt.xlabel('Unemployment Rate')
plt.ylabel('Frequency')
plt.show()

top_regions = data.groupby('Region')[unemployment_rate_column].mean().sort_values().tail(5).index
sns.boxplot(x='Region', y=unemployment_rate_column, data=data[data['Region'].isin(top_regions)])

sns.boxplot(x='Region', y=unemployment_rate_column, data=data.groupby('Region')[unemployment_rate_column].mean().reset_index())

sns.lineplot(x=' Date', y=' Estimated Unemployment Rate (%)', hue='Region', data=data)
plt.title('Unemployment Rate Over Time by Region')
plt.xlabel('Date')
plt.ylabel('Unemployment Rate (%)')
plt.legend(title='Region', loc='upper left', bbox_to_anchor=(1, 1))
plt.show()

sns.boxplot(x=' Date', y=unemployment_rate_column, data=data)

sns.lineplot(x=' Date', y=' Estimated Unemployment Rate (%)', data=data)
plt.title('Unemployment Rate Over Time')
plt.xlabel('Date')
plt.ylabel('Unemployment Rate (%)')
plt.show()

plt.figure(figsize=(12, 10))
plt.title("unemployment")
sns.histplot(x=" Estimated Unemployment Rate (%)", hue="Region", data=data)
plt.show()

unemployment = data[["Region", " Estimated Employed"]]
figure = px.sunburst(
    unemployment,
    path=["Region"],
    values=" Estimated Employed",
    width=700,
    height=700,
    color_continuous_scale="RdYlGn",
    title="Jobless Rate in India by Region",
)
figure.show()